### PR TITLE
Landing page created (again....)

### PR DESCRIPTION
**Pull request by AbhinavRajputEXE**
Issue #3 
continuation of PR #24 
For Screenshots and a description of proof refer back to PR #24

### CODE REVIEW

**Comment by AbhinavRajputEXE** [comment]
Before other's PR merger, my PR does not have any conflicts 
**PROOF** image:
Screenshot 2023-04-09 at 22 54 48

**Comment by Codey001** [comment]
can u make the pull request again

**Comment by AbhinavRajputEXE** [comment]
> can u make the pull request again

Screenshot 2023-04-10 at 00 09 31


This Existing CSS file have multiple problems which were merged before my PR hence conflicts occurred and this PR was created by @MrJay07 
this file was not not rebased properly before

**Comment by AbhinavRajputEXE** [comment]
Problems can also be viewed in the deployed site here in the footer:
Screenshot 2023-04-10 at 00 14 10

Please take a quick look at the files before we merge them. Thanks

**Pull request merged**
